#
# PRODUCTION
#
production:
  main:
    adapter: postgresql
    encoding: UTF8
    database: gitlabhq_production
    username: git
    password: "secure password"
    host: postgresql
    # load_balancing:
    #   hosts:
    #     - host1.example.com
    #     - host2.example.com
    #   discover:
    #     nameserver: 1.2.3.4
    #     port: 8600
    #     record: secondary.postgresql.service.consul
    #     interval: 300
  # geo:
  #   adapter: postgresql
  #   encoding: UTF8
  #   database: gitlabhq_geo_production
  #   username: git
  #   password: "secure password"
  #   host: postgresql

#
# Development specific
#
development:
  main:
    adapter: postgresql
    encoding: UTF8
    database: gitlabhq_development
    username: postgres
    password: "secure password"
    host: postgresql
    variables:
      statement_timeout: 15s
  # geo:
  #   adapter: postgresql
  #   encoding: UTF8
  #   database: gitlabhq_geo_development
  #   username: postgres
  #   password: "secure password"
  #   host: postgresql

#
# Staging specific
#
staging:
  main:
    adapter: postgresql
    encoding: UTF8
    database: gitlabhq_staging
    username: git
    password: "secure password"
    host: postgresql
  # geo:
  #   adapter: postgresql
  #   encoding: UTF8
  #   database: gitlabhq_geo_staging
  #   username: git
  #   password: "secure password"
  #   host: postgresql

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  main:
    adapter: postgresql
    encoding: UTF8
    database: gitlabhq_test
    username: postgres
    password:
    host: postgresql
    prepared_statements: false
    variables:
      statement_timeout: 15s
  # geo:
  #   adapter: postgresql
  #   encoding: unicode
  #   database: gitlabhq_geo_test
  #   username: postgres
  #   password:
  #   host: postgresql
