#!/bin/bash
set -e

DockerFile=all-in-one/Dockerfile

echo "note: you should run this in top directory of this repo."
echo -e "" > ${DockerFile} # clear

cat >> ${DockerFile}  <<EOF
# This Dockerfile is generated by all-in-one script.
# This Dockerfile this a collection of all other splited Dockerfiles, but except gitlab-pages docker image.
# You can use this Dockerfile only to build gitlab-ce docker image.

################################
## image of gitlab-base-builder
################################
EOF
# builder
cat builder/Dockerfile >> ${DockerFile}


cat >> ${DockerFile}  <<EOF

################################
## image of gitlab-shell-builder
################################
EOF
cat gitlab-shell/Dockerfile >> ${DockerFile}


cat >> ${DockerFile}  <<EOF

################################
## image of gitlab-workhorse-builder
################################
EOF
cat gitlab-workhorse/Dockerfile >> ${DockerFile}


cat >> ${DockerFile}  <<EOF

################################
## image of gitlab-gitaly-builder
################################
EOF
cat gitaly/Dockerfile >> ${DockerFile}


cat >> ${DockerFile}  <<EOF

################################
## image of gitlab-builder
################################
EOF
cat gitlab/Dockerfile >> ${DockerFile}


cat >> ${DockerFile}  <<EOF

################################
## image of genshen/gitlab-ce
################################
EOF
cat Dockerfile >> ${DockerFile}

echo "success!"
